[project]
name = "pahe-encoder-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.2.5",
    "streamlit>=1.45.0",
]
